# Generated by Django 2.2.2 on 2019-07-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20190710_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='contact_way',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='note_count',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='sex',
        ),
    ]
