# Generated by Django 2.2.2 on 2019-07-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_auto_20190728_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='access_last_time',
        ),
    ]
