# Generated by Django 2.2.2 on 2019-07-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default=' ', max_length=300, verbose_name='概要'),
        ),
    ]
