# Generated by Django 2.2.2 on 2019-08-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtherApp', '0002_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
