# Generated by Django 2.2.2 on 2019-08-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OtherApp', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='father_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='OtherApp.Note', verbose_name='回复留言的id'),
        ),
    ]
