# Generated by Django 2.2.2 on 2019-08-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtherApp', '0005_note_father_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='father_id',
            new_name='father',
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, '公开留言'), (0, '私信'), (2, '建议')], default=1, null=True, verbose_name='留言类型'),
        ),
    ]
