# Generated by Django 2.2.2 on 2019-07-07 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('copyright', models.BooleanField(default=True, verbose_name='原创/转载')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('access_count', models.IntegerField(default=0, verbose_name='总访问量')),
                ('like_count', models.IntegerField(default=0, verbose_name='喜欢数')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('type', models.PositiveIntegerField(choices=[(1, '公开留言'), (0, '私信'), (2, '建议')], default=1, verbose_name='留言类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.UserAccount', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.Article', verbose_name='评论文章')),
                ('father_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.ArticleComment', verbose_name='回复')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.UserAccount', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.Category', verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='ArticleApp.Tag', verbose_name='标签'),
        ),
    ]
