# Generated by Django 2.2.2 on 2019-07-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ImageFile',
            field=models.ImageField(upload_to='article/'),
        ),
    ]
