# Generated by Django 2.2.2 on 2019-08-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0009_specialcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTopic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('like_account', models.IntegerField(default=0, verbose_name='点赞')),
                ('summary', models.CharField(max_length=1000, verbose_name='专题介绍')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialColumn',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ArticleApp.Category', verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ArticleApp.SpecialTopic', verbose_name='专题'),
        ),
    ]
