# Generated by Django 2.2.2 on 2019-08-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0011_auto_20190807_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
