# Generated by Django 2.2.1 on 2019-08-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0014_auto_20190813_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtopic',
            name='articles',
            field=models.ManyToManyField(to='ArticleApp.Article', verbose_name='专栏文章'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='specialtopic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
