# Generated by Django 2.2.2 on 2019-07-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrangeUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(verbose_name='陌生用户的UID')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问本站次数')),
                ('access_article_count', models.IntegerField(default=0, verbose_name='浏览文章次数')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='昵称')),
                ('sex', models.PositiveIntegerField(choices=[(0, '帅哥'), (1, '美女')], default=0, verbose_name='性别')),
                ('contact_way', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式')),
                ('password', models.CharField(max_length=6, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('access_last_time', models.DateTimeField(auto_now_add=True, verbose_name='上次访问时间')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论次数(包括回复)')),
                ('note_count', models.IntegerField(default=0, verbose_name='留言次数')),
            ],
        ),
    ]
