# Generated by Django 2.2.2 on 2019-07-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strangeuser',
            name='access_article_count',
        ),
    ]
