# Generated by Django 2.2.2 on 2019-07-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_remove_strangeuser_access_article_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strangeuser',
            name='uid',
            field=models.CharField(max_length=100, verbose_name='陌生用户的UID'),
        ),
    ]
