# Generated by Django 2.2.2 on 2019-07-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20190711_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='username',
        ),
    ]
