# Generated by Django 2.2.2 on 2019-07-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20190724_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='access_count',
            field=models.IntegerField(default=1, verbose_name='访问本站次数'),
        ),
        migrations.AlterField(
            model_name='strangeuser',
            name='access_count',
            field=models.IntegerField(default=1, verbose_name='访问本站次数'),
        ),
    ]
