# Generated by Django 2.2.2 on 2019-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_auto_20190727_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strangeuser',
            name='access_count',
            field=models.IntegerField(default=0, verbose_name='访问本站次数'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='access_count',
            field=models.IntegerField(default=0, verbose_name='访问本站次数'),
        ),
    ]
