# Generated by Django 2.2.2 on 2019-08-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_remove_useraccount_access_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strangeuser',
            name='uid',
            field=models.CharField(max_length=100, verbose_name='陌生用户的ip'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
    ]
